### PR TITLE
Basic Cisco ASA support

### PR DESCRIPTION
**Pull request by DiogoAndre**
Basic Cisco ASA Driver for NAPALM. 

related to napalm-automation/napalm/issues/318

### CODE REVIEW

**Comment by ogenstad** [comment]
Nice work @DiogoAndre! Just looking skimming the code there are a few things I can comment on.

First you are using the old test framework, to save time later and not have to recreate the mock data it would be better to use the new framework (the one used by napalm-eos and napalm-ios).

Secondly it can be a good idea to write the code to be compliant with both Python 2 and Python 3 at the same time, this also saves time if it's done from the start.

Just looking at the code my only real comment is around this line:
``` Python
ssl._create_default_https_context = ssl._create_unverified_context
```
First I think this requires Python 2.7.9. I'm not really sure about which version of Python 2.7 that Napalm targets. Granted 2.7.9 is quite old but a lot of distros still doesn't use that version. More importantly I don't think it's a good idea to ignore the certificate security. While I don't know how other Napalm drivers which use https handle certificates. It would be a good idea to keep that behaviour consistent, in terms of setting trusted certificates and such.

A thing to consider later on with the config operations is something like this which would be valid with the other Napalm drivers:
```
clear configure access-list ACL-INSIDE-V5
access-list ACL-INSIDE-V5 remark --- Traffic from NET-SOHO-PATRICK to INTERNET
access-list ACL-INSIDE-V5 remark - ICMP/8, ECHO
access-list ACL-INSIDE-V5 extended permit icmp object-group NET-SOHO-PATRICK object-group INTERNET echo
access-list ACL-INSIDE-V5 remark - TCP/21, FTP
access-list ACL-INSIDE-V5 extended permit tcp object-group NET-SOHO-PATRICK object-group INTERNET eq ftp
access-list ACL-INSIDE-V5 remark - TCP/22, SSH
access-list ACL-INSIDE-V5 extended permit tcp object-group NET-SOHO-PATRICK object-group INTERNET eq ssh

access-list ACL-WORK-V1 remark - TCP/443, HTTPS
access-list ACL-WORK-V1 extended permit tcp object-group NET-WORK object-group INTERNET eq https

crypto ikev2 policy 50
 encryption 3des
 integrity sha
 group 2
 prf sha
 lifetime seconds 86400
```

Where we have an access-list ACL-INSIDE-V5 which we want to ensure it looks exactly like shown above, while for ACL-WORK-V1 we only want to make sure that https is permitted but we don't care about what the rest of the access-list looks like. As an example we also want a specific ikev2 policy created. In order to make this idempotent the driver would first have to parse the input and figure out if the ACL-INSIDE-V5 looks like we want it to do below the clear configure line. For that part of the config do a replace operation in the API, for the ACL-WORK-V1 it would need an update/patch operation. It might be that something like Jason suggested will be needed to handle this in a simple way.

**Comment by dbarrosop** [comment]
Yes, please, use the new testing framework. I have to finish the cookiecutter project so new drivers start off with the correct code, sorry about that : (

Also, is there any possibility to get a vagrant box or a vm for testing?

**Comment by dbarrosop** [comment]
> `ssl._create_default_https_context = ssl._create_unverified_context`

We could have an optional argument to control that.

**Comment by DiogoAndre** [comment]
Thanks guys.  I'll take a look at the new test framework. I saw the discussion around it, but didn't follow closely. 

I see what is possible on the ssl area. It sure is not a great idea to trust unverified certs by default.

As for the Vagrant box/vm,  Cisco provides an .ovf for the ASAv platform, so it is not very complicated to run it locally. However, download of the .ovf is only permitted if you have a valid Cisco service contract, I believe.

**Comment by dbarrosop** [comment]
Is there any VM we can use to test the driver?

**Comment by DiogoAndre** [comment]
Yes.. I'll try to compile some instructions on how to run a ASAv VM, and see if I can create a Vagrant box for it.

**Comment by dbarrosop** [comment]
Any update on the testing instructions? Or did I miss something?

**Comment by bobthebutcher** [comment]
Not sure if this project is still going, I stumbled across it when I was poking around, seems to be getting a bit long in the tooth since the last update. I wrote a blog post on how to build an ASAv vagrant box here: https://codingpackets.com/blog/cisco-asa-vagrant-box-install/ might be of use if you don't one setup already.

**Comment by dbarrosop** [comment]
I am going to merge this in the branch `DiogoAndre:basic-asa` in case someone wants to take over

**Comment by DiogoAndre** [comment]
HI @bobthebutcher, your write up looks great. I will write a better readme for the driver and add a link to your site for the vagrant instructions. Cheers!

**Pull request merged**
